/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.codigodebarra.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Yoshua
 */
public class JInformacion extends javax.swing.JDialog {

    /**
     * Creates new form JInformacion
     */
    public JInformacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtNombreProd = new javax.swing.JTextField();
        txtCompaniaProd = new javax.swing.JTextField();
        txtContenidoProd = new javax.swing.JTextField();
        txtCantidadProd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblPreguntar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreProd.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        jPanel1.add(txtNombreProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 220, -1));

        txtCompaniaProd.setBorder(javax.swing.BorderFactory.createTitledBorder("Compañía"));
        jPanel1.add(txtCompaniaProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 220, -1));

        txtContenidoProd.setBorder(javax.swing.BorderFactory.createTitledBorder("Contenido"));
        jPanel1.add(txtContenidoProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 120, 40));

        txtCantidadProd.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad"));
        jPanel1.add(txtCantidadProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 90, 40));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 280, 170));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Información del producto");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 34, -1, 38));
        jPanel2.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 300, 217));

        btnAceptar.setText("Aceptar");
        jPanel2.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 109, 35));

        btnCancelar.setText("Cancelar");
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 96, 35));

        lblPreguntar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(lblPreguntar, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 313, 541, 41));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JInformacion dialog = new JInformacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public void setBtnAceptar(JButton btnAceptar) {
        this.btnAceptar = btnAceptar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return lblPreguntar;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.lblPreguntar = jLabel2;
    }

    public JLabel getLblImagen() {
        return lblImagen;
    }

    public void setLblImagen(JLabel lblImagen) {
        this.lblImagen = lblImagen;
    }

    public JLabel getLblPreguntar() {
        return lblPreguntar;
    }

    public void setLblPreguntar(JLabel lblPreguntar) {
        this.lblPreguntar = lblPreguntar;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JTextField getTxtCantidadProd() {
        return txtCantidadProd;
    }

    public void setTxtCantidadProd(JTextField txtCantidadProd) {
        this.txtCantidadProd = txtCantidadProd;
    }

    public JTextField getTxtCompaniaProd() {
        return txtCompaniaProd;
    }

    public void setTxtCompaniaProd(JTextField txtCompaniaProd) {
        this.txtCompaniaProd = txtCompaniaProd;
    }

    public JTextField getTxtContenidoProd() {
        return txtContenidoProd;
    }

    public void setTxtContenidoProd(JTextField txtContenidoProd) {
        this.txtContenidoProd = txtContenidoProd;
    }

    public JTextField getTxtNombreProd() {
        return txtNombreProd;
    }

    public void setTxtNombreProd(JTextField txtNombreProd) {
        this.txtNombreProd = txtNombreProd;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblPreguntar;
    private javax.swing.JTextField txtCantidadProd;
    private javax.swing.JTextField txtCompaniaProd;
    private javax.swing.JTextField txtContenidoProd;
    private javax.swing.JTextField txtNombreProd;
    // End of variables declaration//GEN-END:variables
}
